### PR TITLE
Authentification Back OK

### PR DESCRIPTION
**Pull request by LauraCourquin**

### CODE REVIEW

**Review by ghost — DISMISSED** [review]

**Review by LuigiMenez — DISMISSED** [review]
Ok for me.

**Comment by LoicBrassart** [comment]
Plz solve conflicts

**Review by ghost — APPROVED** [review]

**Review by LuigiMenez — APPROVED** [review]
Ok for me.

**Review by LoicBrassart — APPROVED** [review]
SnE

**Pull request merged**
