### PR TITLE
refactoring the code to make the component more independant of the page

### PR DESCRIPTION
**Pull request by camillaume**

### CODE REVIEW

**Review by ghost — DISMISSED** [review]
ok for me

**Review by LoicBrassart — DISMISSED** [review]
SnE

**Review by LuigiMenez — DISMISSED** [review]
Ok for me.

**Comment by ghost** [comment]
fix style search conflict

**Review by ghost — APPROVED** [review]

**Review by LuigiMenez — APPROVED** [review]
Ok for me

**Review by LoicBrassart — APPROVED** [review]
SnE

**Pull request merged**
