### PR TITLE
adding content to the about page to ease navigaation

### PR DESCRIPTION
**Pull request by camillaume**

### CODE REVIEW

**Review by ghost — DISMISSED** [review]
Ok for me

**Review by LuigiMenez — DISMISSED** [review]
Ok.

**Review by LoicBrassart — DISMISSED** [review]
SnE

**Comment by ghost** [comment]
u already accept this PR but we have a conflict on app, i fixed it, can u approve this PR (again) plz ? sorry for that

**Review by LuigiMenez — APPROVED** [review]
Ok for me.

**Review by LoicBrassart — APPROVED** [review]
SnE

**Review by ghost — APPROVED** [review]
ok for me

**Pull request merged**
